-- Alle Tabellen löschen
DROP VIEW  IF EXISTS posts_v;
DROP VIEW  IF EXISTS cat_posts_v;
DROP TABLE IF EXISTS posts;
DROP TABLE IF EXISTS cat_posts;

-- Tabelle Posten
CREATE TABLE IF NOT EXISTS cat_posts (
    id          SERIAL,
    designation VARCHAR(30) NOT NULL,
    description VARCHAR(50),
    rank        CHAR(1),
    pg_id       INT,
    transfer    BOOL     DEFAULT FALSE,
    cash        BOOL     DEFAULT FALSE,
    active      BOOL     DEFAULT TRUE,
    CONSTRAINT  pk_pd    PRIMARY KEY (id),
    CONSTRAINT  fk_pd_pg FOREIGN KEY (pg_id)
    REFERENCES  cat_postgroups (id)
);

-- Tabelle leeren
DELETE FROM cat_posts;

-- Tabelle füllen
INSERT INTO cat_posts (designation, rank, transfer, cash, pg_id, description)
VALUES ('Handys',                 'a', TRUE,  TRUE,   1, ''),
       ('Fahrtickets',            'b', TRUE,  TRUE,   1, ''),
       ('Russische Schule',       'a', TRUE,  FALSE,  2, ''),
       ('Deutsche Schule',        'b', TRUE,  TRUE,   2, ''),
       ('KiTa',                   'c', TRUE,  FALSE,  2, 'Essen im Kindergarten'),
       ('Ausflüge',               'd', TRUE,  TRUE,   2, ''),
       ('Anastasias Taschengeld', 'e', TRUE,  TRUE,   2, ''),
       ('Ekaterinas Taschengeld', 'f', TRUE,  FALSE,  2, ''),
       ('Stefanies Taschengeld',  'g', FALSE, TRUE,   2, ''),
       ('Vielseitigkeit',         'h', TRUE,  FALSE,  2, 'Tanzen, Kunst...'),
       ('Sportaktivität',         'i', TRUE,  FALSE,  2, ''),
       ('Schreibwaren',           'j', TRUE,  TRUE,   2, ''),
       ('Technik für Kinder',     'k', TRUE,  TRUE,   2, 'Players, Handys, …'),
       ('Tanken',                 'a', TRUE,  TRUE,   3, ''),
       ('Reparatur-Service',      'b', FALSE, TRUE,   3, ''),
       ('Steuer',                 'c', TRUE,  FALSE,  3, ''),
       ('Versicherung',           'd', TRUE,  FALSE,  3, ''),
       ('TÜV',                    'e', FALSE, TRUE,   3, ''),
       ('Straffe',                'f', TRUE,  FALSE,  3, ''),
       ('Restausgaben',           'g', FALSE, TRUE,   3, ''),
       ('Discounter',             'a', TRUE,  TRUE,   4, 'ALDI, LIDL,…'),
       ('Supermärkte',            'b', TRUE,  TRUE,   4, 'REWE, Kaufland, Edeka,…'),
       ('Sonstige LMG',           'c', TRUE,  TRUE,   4, 'Russische, tuerkische Geschaefte, Maerkte,…'),
       ('Haushalt',               'a', TRUE,  TRUE,   5, 'Rossmann, dm, Müller, …'),
       ('Zähne',                  'b', TRUE,  TRUE,   5, ''),
       ('Gesundheit',             'c', TRUE,  TRUE,   5, 'Apotheke'),
       ('Pflege',                 'd', FALSE, TRUE,   5, 'Friseuse'),
       ('Kleidung',               'a', TRUE,  TRUE,   6, ''),
       ('Schuhe',                 'b', TRUE,  TRUE,   6, ''),
       ('Haushaltgeräte',         'a', TRUE,  TRUE,   7, 'Staubsauger, Fernseher,…'),
       ('Möbel',                  'b', TRUE,  TRUE,   7, ''),
       ('Komputertechnik',        'c', TRUE,  TRUE,   7, ''),
       ('Vermögenswerte',         'd', FALSE, TRUE,   7, 'Leiter, Teppich,…'),
       ('Hobby',                  'a', TRUE,  TRUE,   8, ''),
       ('Essen',                  'b', FALSE, TRUE,   8, ''),
       ('Kultur',                 'c', FALSE, TRUE,   8, 'Museen, Kinos, Theater,..'),
       ('Parks',                  'd', FALSE, TRUE,   8, 'Aqua-, Naturparks,…'),
       ('Sport',                  'e', FALSE, TRUE,   8, 'Sportaktivität von Erwachsenen'),
       ('Unterhalt',              'a', TRUE,  TRUE,   9, ''),
       ('Unterkunft',             'b', TRUE,  TRUE,   9, 'Wohnungsmiete'),
       ('Tafel',                  'c', TRUE,  TRUE,   9, 'Cafes, Restauranten'),
       ('Katze',                  'a', TRUE,  TRUE,  10, ''),
       ('Schrebergarten',         'b', TRUE,  TRUE,  10, ''),
       ('Geburtstage',            'a', TRUE,  TRUE,  11, ''),
       ('Feiertage',              'b', TRUE,  TRUE,  11, ''),
       ('Warmmiete',              'a', TRUE,  FALSE, 12, ''),
       ('Elektrizität',           'b', TRUE,  FALSE, 12, ''),
       ('Internet',               'c', TRUE,  FALSE, 12, ''),
       ('Renovierung',            'd', TRUE,  FALSE, 12, ''),
       ('Rundfunk',               'e', TRUE,  FALSE, 12, 'Westdeutscher Rundfunk Köln'),
       ('Netflix',                'f', TRUE,  FALSE, 12, ''),
       ('Bankgebür',              'a', TRUE,  TRUE,  13, ''),
       ('Baumarkt',               'b', FALSE, FALSE, 13, ''),
       ('Sonstiges',              'c', TRUE,  FALSE, 13, ''),
       ('Korrigierung',           'd', FALSE, FALSE, 13, ''),
       ('Dimas Gehalt',           'a', TRUE,  FALSE, 14, ''),
       ('Lisas Lohn',             'b', TRUE,  FALSE, 14, ''),
       ('Urlaubsgeld',            'c', TRUE,  FALSE, 14, ''),
       ('Weihnachtsgeld',         'd', TRUE,  FALSE, 14, ''),
       ('Dima LV',                'e', TRUE,  FALSE, 14, 'Leistung für Vermögen 40 €'),
       ('Lisa LV',                'f', TRUE,  FALSE, 14, 'Leistung für Vermögen 40 €'),
       ('Prämie',                 'g', TRUE,  FALSE, 14, ''),
       ('Vermögensberatung',      'h', TRUE,  FALSE, 14, ''),
       ('Kindergeld',             'a', TRUE,  FALSE, 15, ''),
       ('Hilfe',                  'b', TRUE,  FALSE, 15, 'CoronaBonus'),
       ('Geldgeschenke',          'a', TRUE,  TRUE,  16, ''),
       ('Nebenjob',               'b', TRUE,  TRUE,  16, ''),
       ('Verkaufen',              'c', TRUE,  TRUE,  16, ''),
       ('Artem',                  'd', TRUE,  TRUE,  16, 'Für Internet'),
       ('Stadt Dortmund',         'e', TRUE,  TRUE,  16, ''),
       ('Erstattungen',           'f', TRUE,  TRUE,  16, ''),
       ('ALG-II',                 'a', TRUE,  FALSE, 17, ''),
       ('Schulgeld',              'b', TRUE,  FALSE, 17, ''),
       ('Prämie JC',              'c', TRUE,  FALSE, 17, ''),
       ('Fahrgelderstattung',     'd', TRUE,  FALSE, 17, ''),
       ('Sonstige Zahlungen',     'e', TRUE,  FALSE, 17, 'Coronabonus, …'),
       ('Anfangsstand',           'a', FALSE, FALSE, 18, ''),
       ('Barauszahlung',          'a', TRUE,  FALSE, 19, ''),
       ('Kartenzahlung',          'b', TRUE,  FALSE, 19, ''),
       ('Geldeinlegen',           'c', TRUE,  FALSE, 19, ''),
       ('Überweisungen',          'd', TRUE,  FALSE, 19, 'Geldverkehr zwischen den Konten'),
       ('BauSparVertrag1500',     'e', TRUE,  FALSE, 19, ''),
       ('BauSparVertrag500',      'f', TRUE,  FALSE, 19, ''),
       ('Vermögensaufbau Lisa',   'g', TRUE,  FALSE, 19, '100€ monatlich'),
       ('Vermögensaufbau Dima',   'h', TRUE,  FALSE, 19, '100€ monatlich'),
       ('Mein Zukunft Anastasia', 'i', TRUE,  FALSE, 19, '80€ monatlich'),
       ('Mein Zukunft Ekaterina', 'j', TRUE,  FALSE, 19, '60€ monatlich'),
       ('Mein Zukunft Stefanie',  'k', TRUE,  FALSE, 19, '50€ monatlich');